name: Publish MS Utils
on: [push]
permissions:
  contents: read
  packages: write
jobs:
  build:
    strategy:
      matrix:
        java: [
          21
        ]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Get version
        id: version
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: gradle.properties
          property: projectVersion
          default: 0.0.1
      - name: Check if version is published
        id: check-published
        uses: mukunku/tag-exists-action@v1.6.0
        with:
          tag: v${{ steps.version.outputs.projectVersion }}
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', '**/settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: build
        if: steps.check-published.outputs.exists == 'true'
        run: ./gradlew build
      - name: gradle publish
        if: steps.check-published.outputs.exists == 'false'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}